server:
  port: 8080
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/300523_m_be_hotel
    username: root
    password: Welcome!1

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
